CREATE TABLE accounts
(
    account_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT   NOT NULL,

    balance      BIGINT NOT NULL
);

CREATE TABLE sessions
(
    session_id UUID PRIMARY KEY     DEFAULT uuidv7(),
    account_id BIGINT      NOT NULL REFERENCES accounts (account_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + interval '30 minutes'
);

CREATE TABLE stocks
(
    stock_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_name TEXT NOT NULL
);

CREATE TABLE account_stocks
(
    account_id BIGINT REFERENCES accounts (account_id),
    stock_id   BIGINT REFERENCES stocks (stock_id),
    quantity   BIGINT NOT NULL CHECK (quantity >= 0),

    PRIMARY KEY (account_id, stock_id)
);

CREATE TYPE order_action AS ENUM ('buy', 'sell');

CREATE TABLE account_orders
(
    account_id      BIGINT REFERENCES accounts (account_id),
    stock_id        BIGINT REFERENCES stocks (stock_id),
    quantity        BIGINT       NOT NULL CHECK (quantity >= 0),
    quantity_filled BIGINT       NOT NULL DEFAULT 0 CHECK (quantity_filled >= 0),
    limit_price     BIGINT       NOT NULL,
    action          order_action NOT NULL
);