CREATE TABLE accounts (
    account_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name TEXT NOT NULL,

    x BIGINT NOT NULL,
    y BIGINT NOT NULL
);

CREATE TABLE sessions (
    session_id UUID PRIMARY KEY     DEFAULT uuidv7(),
    account_id BIGINT      NOT NULL REFERENCES accounts (account_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + interval '30 minutes'
);